name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build (${{ matrix.os }}, ${{ matrix.mode }}, Go ${{ matrix.go }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        mode: [release, dev]
        go: ["1.14"]

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build deej (Windows)
        if: runner.os == 'Windows'
        run: pkg/deej/scripts/windows/build-${{ matrix.mode }}.bat
        shell: cmd

      - name: Upload Windows artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: deej-windows-${{ matrix.mode }}
          path: |
            deej.exe
            config.yaml
          if-no-files-found: warn
